// <auto-generated />
namespace RMarket.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renameSettingType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameSettingType));
        
        string IMigrationMetadata.Id
        {
            get { return "201607211829029_renameSettingType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
